gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all_empresa:
    path:     /empresa/all
    defaults: { _controller: gestorBundle:empresa:all }

empresa_crear:
    path:     /empresa/new
    defaults: { _controller: gestorBundle:empresa:crearEmpresa }