gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all_empresa:
    path:     /empresa/all
    defaults: { _controller: gestorBundle:empresa:all }

registrar_usuario:
    path:     /register
    defaults: { _controller: gestorBundle:register:registrar }

Usuario_Registrado:
    path:     /register/msgExito
    defaults: { _controller: gestorBundle:register:msgExito }

Usuarios:
    path:     /usuarios
    defaults: { _controller: gestorBundle:usuarios:usuarios }

login:
    path:     /usuarios/login
    defaults: { _controller: gestorBundle:usuarios:login}

#empresa_crear:
 #   path:     /empresa/new
 #   defaults: { _controller: gestorBundle:empresa:crearEmpresa }

empresa_nueva:
    path:     /empresa/new
    defaults: { _controller: gestorBundle:empresa:nuevaEmpresa }

empresa_msgExito:
    path:     /empresa/msgExito
    defaults: { _controller: gestorBundle:empresa:msgExito }

alumnosAll:
  path:       /alumno/all
  defaults: { _controller: gestorBundle:alumno:alumnosAll }

jsonempresas:
    path: /empresas
    defaults: {_controller: gestorBundle:empresasAPI:generarJSON}
    methods: [GET]
